from pydantic import BaseModel, Field
from typing import Optional


class RagRequest(BaseModel):
    query: str = Field(...,
                       description="The query to be processed by the RAG system.")


class RAGUsedContext(BaseModel):
    image_url: str = Field(
        description="URL of the image used to answer the question")
    price: Optional[float] = Field(
        description="Price of the item used to answer the question")
    description: str = Field(
        description="Description of the item used to answer the question")


class RagResponse(BaseModel):
    request_id: str = Field(...,
                            description="A unique identifier for the RAG request.")
    answer: str = Field(
        ..., description="The answer generated by the RAG system in response to the query.")
    used_context: list[RAGUsedContext] = Field(
        ..., description="A list of context items used by the RAG system to generate the answer.")
