from pydantic import BaseModel, Field


class RagRequest(BaseModel):
    query: str = Field(...,
                       description="The query to be processed by the RAG system.")


class RagResponse(BaseModel):
    request_id: str = Field(...,
                            description="A unique identifier for the RAG request.")
    answer: str = Field(
        ..., description="The answer generated by the RAG system in response to the query.")
